microsoft/windows-ai-studio-templates

inference_models.json
Related: https://github.com/microsoft/Skylight/pull/162
=> Rename type to task

inference_models.json
See https://github.com/microsoft/Skylight/pull/167
=> feat: add inference => finetuning project template name mapping

configs/Phi-3-mini-4k-instruct/infra/finetuning.config.json, configs/Phi-3-mini-4k-instruct/infra/provision/finetuning.bicep, configs/Phi-3-mini-4k-instruct/infra/provision/finetuning.parameters.json, configs/mistral-7b/infra/finetuning.config.json, configs/mistral-7b/infra/provision/finetuning.bicep, configs/mistral-7b/infra/provision/finetuning.parameters.json, configs/phi-2/infra/finetuning.config.json, configs/phi-2/infra/provision/finetuning.bicep, configs/phi-2/infra/provision/finetuning.parameters.json
Remove the hugging face secret and env in bicep. User can add huggingface secret in another command.
=> fix: remove huggingface secret in bicep

configs/Phi-3-mini-4k-instruct/infra/provision/finetuning.bicep, configs/Phi-3-mini-4k-instruct/infra/provision/finetuning.parameters.json, configs/Phi-3-mini-4k-instruct/infra/provision/inference.bicep, configs/Phi-3-mini-4k-instruct/infra/provision/inference.parameters.json, configs/mistral-7b/infra/provision/finetuning.bicep, configs/mistral-7b/infra/provision/finetuning.parameters.json, configs/mistral-7b/infra/provision/inference.bicep, configs/mistral-7b/infra/provision/inference.parameters.json, configs/phi-2/infra/provision/finetuning.bicep, configs/phi-2/infra/provision/finetuning.parameters.json, configs/phi-2/infra/provision/inference.bicep, configs/phi-2/infra/provision/inference.parameters.json
Increase the default GPU instance number
=> feat: increase GPU instance number

inference_models.json
Add metadata from Ximena's design for existing models.
=> feat: Add inference model metadata

configs/Phi-3-mini-4k-instruct/README.md, configs/llama-v2-7b/README.md, configs/mistral-7b/README.md, configs/phi-1_5/README.md, configs/phi-2/README.md, configs/zephyr-7b-beta/README.md
Issue: https://github.com/microsoft/Skylight/issues/233
=> docs: add remote development into readme

configs/Phi-3-mini-4k-instruct/infra/provision/finetuning.bicep, configs/Phi-3-mini-4k-instruct/infra/provision/inference.bicep, configs/llama-v2-7b/infra/provision/finetuning.bicep, configs/llama-v2-7b/infra/provision/inference.bicep, configs/mistral-7b/infra/provision/finetuning.bicep, configs/mistral-7b/infra/provision/inference.bicep, configs/phi-1_5/infra/provision/finetuning.bicep, configs/phi-1_5/infra/provision/inference.bicep, configs/phi-2/infra/provision/finetuning.bicep, configs/phi-2/infra/provision/inference.bicep, configs/zephyr-7b-beta/infra/provision/finetuning.bicep, configs/zephyr-7b-beta/infra/provision/inference.bicep
Fix: https://github.com/microsoft/Skylight/issues/232
=> fix: update resource prefix

configs/Phi-3-mini-4k-instruct/README.md, configs/llama-v2-7b/README.md, configs/mistral-7b/README.md, configs/phi-1_5/README.md, configs/phi-2/README.md, configs/zephyr-7b-beta/README.md
Add "View and Query Logs on Azure" link to readme
=> docs: add remote log to readme

schemas/v0.1/sample.yml, schemas/v0.1/yaml.schema.json
Add yaml schema for aitk project yaml.
Add sample as well for dev test.
=> feat: add yaml schema

datasets/new-dataset-using-llm/README.md, datasets/new-dataset-using-llm/create_qa_dataset.py, datasets/new-dataset-using-llm/prompt/qa.prompt
1. Set local inference endpoint as default option
2. Remove the JSON schema response from the QA prompt to enhance the SML experience.
> More results can be find in [here](https://microsoftapc.sharepoint.com/teams/DevDivTeamsDevXProductTeam/_layouts/OneNote.aspx?id=%2Fteams%2FDevDivTeamsDevXProductTeam%2FShared%20Documents%2FService%20infrastructure%20Team%2FInfra%20team&wd=target%28AI%20Toolkit.one%7C36B7B6AB-E79C-43F2-A27D-AF1A23B8A193%2FPhi-3%2C%20GPT-4o%20and%20GPT-4o%20mini%20QA%20compare%7C76DE4004-6450-47D4-9FD0-6D0A5F27AF66%2F%29)
Using large language models(LLM) is a crucial technique in synthetic data generation,
capable of producing high-quality, diverse, and privacy-compliant datasets.
This technique can be applied in different scenarios, including training
machine learning …
=> fix: set local inference endpoint as default

schemas/v0.1/helloworld.yml, schemas/v0.1/sample.yml, schemas/v0.1/yaml.schema.json
- Add simple hello world example
- Adjust fields
=> fix: tweak schema

init/basic/ai-app.yml, init/basic/ai-resource/README.md
To be used by the app init command.
=> feat: add init template

datasets/new-dataset-using-llm/create_qa_dataset.py, datasets/new-dataset-using-llm/prompt/qa.prompt, datasets/new-dataset/create_dataset.py, datasets/new-dataset/dataset.csv
1. Shorter the qa prompt
2. Output jsonl format
=> fix: shorter the prompt and output jsonl

datasets/new-dataset-using-llm/.env.tpl, datasets/new-dataset-using-llm/README.md, datasets/new-dataset-using-llm/create_qa_dataset.py.tpl, datasets/new-dataset-using-llm/requirements.txt
Use mustache template in synthetic data generation template
=> fix: use mustache template in synthetic data generation

evaluation/README.md
Add timestamp to result name, and add instructions to run evaluation and view evaluation results.
=> feat: add README.md to evaluation templates

configs/Phi-3-mini-4k-instruct/infra/provision/inference.parameters.json, configs/llama-v2-7b/infra/provision/inference.parameters.json, configs/llama-v3-8b/infra/provision/inference.parameters.json, configs/mistral-7b-v02/infra/provision/inference.parameters.json, configs/mistral-7b/infra/provision/inference.parameters.json, configs/phi-1_5/infra/provision/inference.parameters.json, configs/phi-2/infra/provision/inference.parameters.json, configs/zephyr-7b-beta/infra/provision/inference.parameters.json
1. Add missing dependency einops in aca inference command
2. Update gradio to fit the new schema
=> fix: update the dependencies in aca inference

tutorials/02_switch_models/README.md, tutorials/03_structured_output/README.md, tutorials/05_evaluate_prompt/app.py, tutorials/05_evaluate_prompt/prompt.aitk.txt
- Add link to launch prompt builder with structure output configuration
- Fix broken link
- Add `prompt.aitk.txt` in evaluation tutorial to automatically activate AITK
=> fix: tutorial readme

model_lab_configs/huggingface/microsoft/resnet-50/1/model_project.config, model_lab_configs/huggingface/microsoft/resnet-50/1/resnet_ptq_qnn.json.config, model_lab_configs/huggingface/openai/clip-vit-base-patch16/1/model_project.config, model_lab_configs/sanitize.py
- Add model info and phase info to project config.
- Process all config versions.
- Fix update issue.
=> Add model info and phase info to project config, process all config versions

model_lab_configs/docs/README-without-AITK.md, model_lab_configs/docs/README.md, model_lab_configs/docs/requirements-AMDNPU.txt, model_lab_configs/docs/requirements-CPU.txt, model_lab_configs/docs/requirements-IntelNPU.txt, model_lab_configs/docs/requirements-QNN.txt
- Provide how to setup venv.
- Introduce project structure.
- Add FAQ.
=> Add readme

.github/workflows/publish-template.yml
Ignore .git and .github folders to reduce the template size
=> fix: do not zip git files

model_lab_configs/model_list.json, model_lab_configs/scripts/sanitize.py
https://github.com/microsoft/Skylight/pull/1986
=> ModelLab: Distinguish HFDataset and LoginRequiredDataset

model_lab_configs/huggingface/Qwen/Qwen2.5-1.5B-Instruct/1/inference_model.json, model_lab_configs/huggingface/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B/1/inference_model.json, model_lab_configs/huggingface/meta-llama/Llama-3.2-1B-Instruct/1/inference_model.json, model_lab_configs/huggingface/microsoft/Phi-3.5-mini-instruct/1/inference_model.json
=> add inference model

model_lab_configs/scripts/sanitize.py
=> fix sanitize print

model_lab_configs/biceps/cloudconversion.wcr.bicep
Upgrade resources (core and memory) for non-LLM model cloud conversion.
=> Update cloud conversion bicep about resources.
